return largest of 3 num
kevinYCKim33/curriculum pull request #2
Opened 2018-01-27 23:19 UTC by kevinYCKim33

2018-01-27 23:32 UTC, seemcat requested changes

2018-01-27 23:32 UTC, seemcat commented on curriculum/js1/2.js
> +  return Math.max(...[a,b,c]);
Nice try! Solve this problem without the max function.

2018-01-27 23:49 UTC, songz commented on curriculum/js1/2.js
> +  } else if (a > b && a > c) {
don't use else if you have returned
```
if (b > a && b > c) {
  return b;
}
if (a > b && a > c ) {
  return a;
}
return c;
```

2018-01-30 04:59 UTC, seemcat commented on curriculum/js1/2.js
> +  } else if (a > b && a > c) {
also, please use recursion.

2018-01-30 05:01 UTC, seemcat requested changes
turn into a recursive function

2018-02-10 23:35 UTC, songz approved these changes

2018-02-10 23:36 UTC, merged