return hello x many times
kevinYCKim33/curriculum pull request #3
Opened 2018-01-27 23:32 UTC by kevinYCKim33

2018-01-27 23:50 UTC, songz commented on curriculum/js1/3.js
> +  for (let i = 0; i < a; i++) {
don't use for loops.

2018-01-30 04:59 UTC, seemcat commented on curriculum/js1/3.js
> +  for (let i = 0; i < a; i++) {
turn this into a recursive function

2018-01-30 05:00 UTC, seemcat requested changes
turn into a recursive function

2018-02-10 23:19 UTC, songz commented on curriculum/js1/3.js
> +  return solution(a-1, result += 'hello')
`result + 'hello'`

2018-02-10 23:30 UTC, songz approved these changes

2018-02-10 23:30 UTC, merged