output string n times
kevinYCKim33/curriculum pull request #4
Opened 2018-01-27 23:49 UTC by kevinYCKim33

2018-01-30 05:00 UTC, seemcat requested changes

2018-01-30 05:00 UTC, seemcat commented on curriculum/js1/4.js
>  };
write this so that it's a recursive function; ALL problems should be answered recursively.

2018-02-10 23:20 UTC, songz requested changes

2018-02-10 23:20 UTC, songz commented on curriculum/js1/4.js
> +  return solution(a-1, b, result+=b)
`result + b`

2018-02-10 23:25 UTC, songz approved these changes

2018-02-10 23:27 UTC, merged